# Generated by Django 6.0.1 on 2026-01-16 12:46

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_credit_score_user_full_name_alter_user_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_rate_monthly', models.DecimalField(decimal_places=6, default=Decimal('0.000300'), max_digits=10)),
                ('min_amount', models.DecimalField(decimal_places=2, default=Decimal('200000.00'), max_digits=14)),
                ('max_amount', models.DecimalField(decimal_places=2, default=Decimal('60000000.00'), max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='loanapplication',
            options={},
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='note',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='tenor_months',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='user',
            name='credit_score',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='age',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='current_living',
            field=models.CharField(default=0, max_length=160),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='full_name',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='guarantor_contact',
            field=models.CharField(default=0, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='guarantor_current_living',
            field=models.CharField(default=0, max_length=160),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='hometown',
            field=models.CharField(default=0, max_length=160),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='id_back',
            field=models.ImageField(blank=True, null=True, upload_to='id_cards/'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='id_front',
            field=models.ImageField(blank=True, null=True, upload_to='id_cards/'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='identity_number',
            field=models.CharField(default=0, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='income',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='income_proof',
            field=models.FileField(blank=True, null=True, upload_to='income_proof/'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='interest_rate_monthly',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='monthly_expenses',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='monthly_repayment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='selfie_with_id',
            field=models.ImageField(blank=True, null=True, upload_to='id_cards/'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='term_months',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('REVIEW', 'In Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='PaymentSchedule',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
