# Generated by Django 6.0.1 on 2026-01-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='withdraw_otp',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
