# Generated by Django 6.0.1 on 2026-01-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_withdraw_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='refunded',
            field=models.BooleanField(default=False),
        ),
    ]
