# Generated by Django 6.0.1 on 2026-01-21 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_withdrawalrequest_refunded'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='otp_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='staff_otp',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
