# Generated by Django 6.0.1 on 2026-01-22 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_withdrawalrequest_otp_required_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_name', models.CharField(blank=True, max_length=120)),
                ('wallet_phone', models.CharField(blank=True, max_length=40)),
                ('bank_name', models.CharField(blank=True, max_length=120)),
                ('bank_account', models.CharField(blank=True, max_length=80)),
                ('paypal_email', models.EmailField(blank=True, max_length=254)),
                ('locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_method', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
