# Generated by Django 6.0.1 on 2026-01-23 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_frozen',
            field=models.BooleanField(default=False),
        ),
    ]
