# Generated by Django 6.0.1 on 2026-01-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_is_frozen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_frozen',
        ),
        migrations.AddField(
            model_name='user',
            name='account_status',
            field=models.CharField(choices=[('active', 'Active'), ('frozen', 'Frozen'), ('rejected', 'Rejected'), ('pending', 'Pending Review'), ('error', 'System Error')], default='active', max_length=20),
        ),
    ]
