# Generated by Django 6.0.1 on 2026-01-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_user_is_frozen_user_account_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status_message',
            field=models.CharField(blank=True, default='', max_length=220),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_status',
            field=models.CharField(choices=[('active', 'Active'), ('frozen', 'Frozen'), ('rejected', 'Rejected'), ('pending_review', 'Pending Review'), ('system_error', 'System Error'), ('low_credit_score', 'Low Credit Score'), ('new_documents_required', 'New Documents Required'), ('tax_verification', 'Tax Verification'), ('vip_channel', 'VIP Channel'), ('overdue', 'Overdue')], default='active', max_length=22),
        ),
    ]
