# Generated by Django 6.0.1 on 2026-01-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_user_status_message_alter_user_account_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('FROZEN', 'Frozen'), ('REJECTED', 'Rejected'), ('NEW_OTP_CODE', 'New OTP code'), ('INVALID_BANK_ACCOUNT', 'Invalid bank account number'), ('LOW_CREDIT_SCORE', 'Low Credit Score'), ('NEW_DOCUMENTS_REQUIRED', 'New Documents Required'), ('TAX_VERIFICATION', 'Tax Verification'), ('VIP_CHANNEL', 'VIP Channel'), ('OVERDUE', 'Overdue')], default='active', max_length=22),
        ),
    ]
