# Generated by Django 6.0.1 on 2026-01-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_user_account_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notification_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='notification_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
