# Generated by Django 6.0.1 on 2026-01-27 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_user_notification_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='loan_purposes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
