# Generated by Django 6.0.1 on 2026-01-29 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_loanapplication_loan_purposes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='success_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='success_message_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
