# Generated by Django 6.0.1 on 2026-01-29 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_user_success_message_user_success_message_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notification_is_read',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='success_is_read',
            field=models.BooleanField(default=True),
        ),
    ]
