# Generated by Django 6.0.1 on 2026-02-02 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_user_notification_is_read_user_success_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='identity_name',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
    ]
