# Generated by Django 6.0.1 on 2026-02-02 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_loanapplication_identity_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
