# Generated by Django 6.0.1 on 2026-02-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_loanapplication_signature_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='register_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='register_country',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
