# Generated by Django 6.0.1 on 2026-02-03 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_withdrawalrequest_ip_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='register_city',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='register_country',
        ),
    ]
