# Generated by Django 6.0.1 on 2026-02-04 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_withdrawalrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('waiting', 'Waiting for approval'), ('reviewed', 'Reviewed'), ('paid', 'Payment sent'), ('rejected', 'Rejected')], default='processing', max_length=20),
        ),
    ]
