# Generated by Django 6.0.1 on 2026-02-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_withdrawalrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='credit_score',
            field=models.PositiveIntegerField(default=650),
        ),
    ]
