# Generated by Django 6.0.1 on 2026-02-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_user_credit_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
