# Generated by Django 6.0.1 on 2026-02-19 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_user_account_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='register_city',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='user',
            name='register_country',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='user',
            name='register_ip',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='register_user_agent',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
