# Generated by Django 6.0.1 on 2026-02-23 21:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_user_register_city_user_register_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanconfig',
            name='interest_rate_monthly',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000500'), max_digits=10),
        ),
    ]
