# Generated by Django 6.0.1 on 2026-02-23 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_alter_loanconfig_interest_rate_monthly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Account Updated', 'Account Updated'), ('Loan Paid', 'Loan Paid'), ('Withdrawal Successful', 'Withdrawal Successful'), ('App Maintenance', 'App Maintenance'), ('Invalid Detail', 'Invalid Detail'), ('LOCKED', 'LOCKED'), ('BANNED', 'BANNED'), ('FROZEN', 'FROZEN'), ('Low Credit', 'Low Credit'), ('Renew Document Required', 'Renew Document Required'), ('Renew OTP Code', 'Renew OTP Code'), ('Renew Document & OTP code', 'Renew Document & OTP code'), ('Overdue Record', 'Overdue Record'), ('Repayment Ability', 'Repayment Ability'), ('VIP Channel', 'VIP Channel'), ('Purchase Life Insurance', 'Purchase Life Insurance'), ('Tax Verification', 'Tax Verification'), ('Platform Fee', 'Platform Fee'), ('AMLC Warning', 'AMLC Warning')], default='Active', max_length=50),
        ),
    ]
