# Generated by Django 6.0.1 on 2026-01-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='account_number',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='bank_name',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='beneficiary_name',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='current_address',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='emergency1_contact',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='emergency1_name',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='emergency2_contact',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='emergency2_name',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='emergency3_contact',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='emergency3_name',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='full_name',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='id_back',
            field=models.ImageField(blank=True, null=True, upload_to='ids/'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='id_front',
            field=models.ImageField(blank=True, null=True, upload_to='ids/'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='monthly_income',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='selfie_with_id',
            field=models.ImageField(blank=True, null=True, upload_to='ids/'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='signature_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('need_doc', 'Need new document'), ('need_otp', 'Need new OTP code')], default='pending', max_length=20),
        ),
    ]
