# Generated by Django 6.0.1 on 2026-01-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_withdrawalrequest_otp_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('otp_sent', 'OTP Sent'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
